var cactus = [['Echinopsis eyriesii',' (Turp.) Zucc.','CR',''],
	['Echinopsis oxygona',' Ritter','VU',''],
	['Epiphyllum phyllanthus',' Kimnach','VU','flor-de-baile'],
	['Frailea albicolumnaris',' F.Ritter','CR','tuna'],
	['Frailea buenekeri',' Abraham','CR','tuna'],
	['Frailea castanea',' Backeb.','CR','tuna'],
	['Frailea curvispina',' Buining & Brederoo','CR','tuna'],
	['Frailea deminuta',' Buining & Brederoo','CR','tuna'],
	['Frailea gracillima',' (Lem.) Britton & Rose','EN','tuna'],
	['Frailea horstii',' F.Ritter','CR','tuna'],
	['Frailea lepida',' Buining & Brederoo','CR','tuna'],
	['Frailea mammifera',' Buining & Brederoo','CR','tuna'],
	['Frailea perumbilicata',' F.Ritter','CR','tuna'],
	['Frailea phaeodisca',' (Speg.) Backeb. & F.M. Knuth','CR','tuna'],
	['Frailea pumila',' (Lem.) Britton & Rose','EN','tuna'],
	['Frailea pygmaea',' (Speg.) Britton & Rose','EN','tuna'],
	['Gymnocalycium buenekeri',' Swales','CR','tuna'],
	['Gymnocalycium denudatum',' (Link & Otto) Pfeiff ex Mittler','CR','tuna'],
	['Gymnocalycium horstii',' Buining','CR','tuna'],
	['Gymnocalycium leeanum',' (Hook.) Britton & Rose','EN','tuna'],
	['Gymnocalycium uruguayense',' (Arechav.) Britton & Rose','CR','tuna'],
	['Hatiora rosea',' (Lagerh.) Barthlott','VU','tuna'],
	['Notocactus arnostianus',' Lisal & Kolarik','CR','tuna'],
	['Notocactus calvescens',' N. Gerloff & A.D. Nilson','CR','tuna'],
	['Notocactus campestrensis',' F.Ritter','VU','tuna'],
	['Notocactus cristatoides',' Ritter','EN','tuna'],
	['Notocactus curvispinus',' F.Ritter','VU','tuna'],
	['Notocactus glomeratus',' N. Gerloff','CR','tuna'],
	['Notocactus gutierrezi',' Abraham','CR','tuna'],
	['Notocactus incomptus',' N. Gerloff','CR','tuna'],
	['Notocactus macambarensis',' Prestle','VU','tuna'],
	['Notocactus miniatispinus',' (F.Ritter) Havlicek','CR','tuna'],
	['Notocactus orthacanthus',' (Link & Otto) Van Vliet','CR','tuna'],
	['Notocactus permutatus',' F.Ritter','CR','tuna'],
	['Notocactus polyacanthus',' (Link & Otto) Theun.','EN','tuna'],
	['Notocactus rauschii',' Vliet','EN','tuna'],
	['Notocactus ritterianus',' Lisal & Kolarik','CR','tuna'],
	['Notocactus rubropedatus',' F.Ritter','VU','tuna'],
	['Notocactus rudibuenekeri',' Abraham','CR','tuna'],
	['Notocactus soldtianus',' Vliet','CR','tuna'],
	['Notocactus spinibarbis',' F.Ritter','CR','tuna'],
	['Notocactus stockingeri',' Prestle','CR','tuna'],
	['Notocactus vilanovaiensis',' N. Gerloff','CR','tuna'],
	['Opuntia brunneogemmia',' (Ritter) C.Schlindwein','VU',''],
	['Opuntia viridirubra',' (F.Ritter) C.Schlindwein','VU',''],
	['Parodia alacriportana',' Backeb. & Voll','CR','tuna'],
	['Parodia allosiphon',' (Marchesi) N.P. Taylor','CR','tuna'],
	['Parodia buiningii',' (Buxb.) N.P. Taylor','CR','tuna'],
	['Parodia caespitosa',' (Speg.) N.P.Taylor','VU','tuna'],
	['Parodia claviceps',' (Ritter) F. H. Brandt','CR','tuna'],
	['Parodia concinna',' (Monv.) N.P.Taylor','CR','tuna'],
	['Parodia crassigiba',' (Ritter)N.P.Taylor','CR','tuna'],
	['Parodia erinacea',' (Haw.) N.P.Taylor','EN','tuna'],
	['Parodia graessneri',' (Schumann)F.H.Brandt','CR','tuna'],
	['Parodia haselbergii',' (Haage) F.H.Brandt','CR','tuna'],
	['Parodia herteri',' (Wedermann)N.P.Taylor','CR','tuna'],
	['Parodia horstii',' (Ritter)N.P.Taylor','CR','tuna'],
	['Parodia langsdorfii',' (Lehm.) D.R. Hunt','VU','tuna'],
	['Parodia leninghausii',' (F.Haage)F.H.Brandt','CR','tuna'],
	['Parodia linkii',' (Lehm.) R.Kiesling','EN','tuna'],
	['Parodia magnifica',' (F.Ritter)F.H.Brandt','CR','tuna'],
	['Parodia mammulosa',' (Lem.) N.P.Taylor','EN','tuna'],
	['Parodia meonacantha',' (Prestle) Hofacker','CR','tuna'],
	['Parodia neohorstii',' (Theun.)N.P.Taylor','CR','tuna'],
	['Parodia ottonis',' (Lehm.) N.P.Taylor','VU','tuna'],
	['Parodia oxycostata',' (Buining & Brederoo) Hofacker','VU','tuna'],
	['Parodia permutata',' (F. Ritter) Hofacker','EN','tuna'],
	['Parodia rechensis',' (Buining)F.H.Brandt','CR','tuna'],
	['Parodia scopa',' (Spreng.) N.P.Taylor','CR','tuna'],
	['Parodia succinea',' (F.Ritter)N.P.Taylor','CR','tuna'],
	['Parodia warasii',' (F.Ritter)F.H.Brandt','CR','tuna'],
	['Pereskia aculeata',' Mill.','VU','ora-pro-nobis'],
	['Rhipsalis paradoxa',' Salm-Dyck','VU','comambaia']
];